const CONSTANTS = {
  INDEX_URL: '/index',
  INDEX_CODE: 'SYS_INDEX',
  TOKEN_KEY: 'JWT-TOKEN',
  ACCESS_TOKEN_KEY: 'OAUTH2-ACCESS-TOKEN',
  ROLES_KEY: 'USER-ROLES',
  USER_KEY: 'LOGIN-USER',
  USER_PERMISSIONS_KEY: 'USER-PERMISSIONS',
  RESOURCES_KEY: 'USER-RESOURCES',
  PRINCIPAL_KEY: 'LOGIN-PRINCIPAL',
  PAGE_SIZE: 10,
  PAGE_LIST: [10, 20, 50, 100],
  state: {
    VALID: '10A',
    INVALID: '10X'
  },
  // 权限编码定义
  authCode: {
    demo: {
      DEMO_BTN_ADD: 'DEMO_BTN_ADD'
    }
  },
  RESP_CODE_SUCESS: '200'
}
export default CONSTANTS
